export default [
  'SUPERIOR',
  'STRONG',
  'UNSTABLE',
  'WISE',
  'YOUNG',
  'OLD',
  'PROTECTOR',
];

export const rewards = [
  'HELMET',
  'CHESTPLATE',
  'LEGGINGS',
  'BOOTS',
  'ASPECT_OF_THE_DRAGONS',
  'LEGENDARY_PET',
  'EPIC_PET',
  'DRAGON_SCALE',
  'DRAGON_CLAW',
  'DRAGON_HORN',
  'FRAGMENTS',
];

export const itemMap = {
  SUPERIOR: {
    HELMET: 'SUPERIOR_DRAGON_HELMET',
    CHESTPLATE: 'SUPERIOR_DRAGON_CHESTPLATE',
    LEGGINGS: 'SUPERIOR_DRAGON_LEGGINGS',
    BOOTS: 'SUPERIOR_DRAGON_BOOTS',
    FRAGMENTS: 'SUPERIOR_FRAGMENT',
  },
  STRONG: {
    HELMET: 'STRONG_DRAGON_HELMET',
    CHESTPLATE: 'STRONG_DRAGON_CHESTPLATE',
    LEGGINGS: 'STRONG_DRAGON_LEGGINGS',
    BOOTS: 'STRONG_DRAGON_BOOTS',
    FRAGMENTS: 'STRONG_FRAGMENT',
  },
  UNSTABLE: {
    HELMET: 'UNSTABLE_DRAGON_HELMET',
    CHESTPLATE: 'UNSTABLE_DRAGON_CHESTPLATE',
    LEGGINGS: 'UNSTABLE_DRAGON_LEGGINGS',
    BOOTS: 'UNSTABLE_DRAGON_BOOTS',
    FRAGMENTS: 'UNSTABLE_FRAGMENT',
  },
  WISE: {
    HELMET: 'WISE_DRAGON_HELMET',
    CHESTPLATE: 'WISE_DRAGON_CHESTPLATE',
    LEGGINGS: 'WISE_DRAGON_LEGGINGS',
    BOOTS: 'WISE_DRAGON_BOOTS',
    FRAGMENTS: 'WISE_FRAGMENT',
  },
  YOUNG: {
    HELMET: 'YOUNG_DRAGON_HELMET',
    CHESTPLATE: 'YOUNG_DRAGON_CHESTPLATE',
    LEGGINGS: 'YOUNG_DRAGON_LEGGINGS',
    BOOTS: 'YOUNG_DRAGON_BOOTS',
    FRAGMENTS: 'YOUNG_FRAGMENT',
  },
  OLD: {
    HELMET: 'OLD_DRAGON_HELMET',
    CHESTPLATE: 'OLD_DRAGON_CHESTPLATE',
    LEGGINGS: 'OLD_DRAGON_LEGGINGS',
    BOOTS: 'OLD_DRAGON_BOOTS',
    FRAGMENTS: 'OLD_FRAGMENT',
  },
  PROTECTOR: {
    HELMET: 'PROTECTOR_DRAGON_HELMET',
    CHESTPLATE: 'PROTECTOR_DRAGON_CHESTPLATE',
    LEGGINGS: 'PROTECTOR_DRAGON_LEGGINGS',
    BOOTS: 'PROTECTOR_DRAGON_BOOTS',
    FRAGMENTS: 'PROTECTOR_FRAGMENT',
  },
  ASPECT_OF_THE_DRAGONS: 'ASPECT_OF_THE_DRAGON',
  LEGENDARY_PET: 'LEGENDARY_ENDER_DRAGON_PET',
  EPIC_PET: 'EPIC_ENDER_DRAGON_PET',
};
