import enumToArray from '../util/enumToArray';
import { IBossReward } from './boss';

export enum SlayerType {
  REVENANT,
  TARANTULA,
  WOLF,
}

export default enumToArray<SlayerType>(SlayerType);

export enum SlayerReward {
  SCYTHE_BLADE,
  SNAKE_RUNE,
  REVENANT_CATALYST,
  BEHEADED_HORROR,
  SMITE_VI_BOOK,
  UNDEAD_CATALYST,
  PESTILENCE_RUNE,
  FOUL_FLESH,
  REVENANT_FLESH,
  DIGESTED_MOSQUITO,
  TARANTULA_TALISMAN,
  FLY_SWATTER,
  BANE_VI_BOOK,
  SPIDER_CATALYST,
  BITE_RUNE,
  TOXIC_ARROW_POISON,
  TARANTULA_WEB,
  OVERFLUX_CAPACITOR,
  GRIZZLY_BAIT,
  RED_CLAW_EGG,
  COUTURE_RUNE,
  CRITICAL_VI_BOOK,
  SPIRIT_RUNE,
  HAMSTER_WHEEL,
  WOLF_TOOTH,
}

export const rewards = enumToArray<SlayerReward>(SlayerReward);

export interface ISlayerReward extends IBossReward {
  reward: SlayerReward;
}

export const itemMap = {
  SCYTHE_BLADE: 'SCYTHE_BLADE',
  SNAKE_RUNE: 'SNAKE_1_RUNE',
  UNDEAD_CATALYST: 'UNDEAD_CATALYST',
  PESTILENCE_RUNE: 'ZOMBIE_SLAYER_1_RUNE',
  SMITE_VI_BOOK: 'SMITE_6_ENCHANTED_BOOK',
  BANE_VI_BOOK: 'BANE_OF_ARTHROPODS_6_BOOK',
  CRITICAL_VI_BOOK: 'CRITICAL_6_BOOK',
  REVENANT_CATALYST: 'REVENANT_CATALYST',
  BEHEADED_HORROR: 'BEHEADED_HORROR',
  FOUL_FLESH: 'FOUL_FLESH',
  DIGESTED_MOSQUITO: 'DIGESTED_MOSQUITO',
  SPIDER_CATALYST: 'SPIDER_CATALYST',
  BITE_RUNE: 'BITE_1_RUNE',
  RED_CLAW_EGG: 'RED_CLAW_EGG',
  COUTURE_RUNE: 'COUTURE_1_RUNE',
  REVENANT_FLESH: 'REVENANT_FLESH',
  TOXIC_ARROW_POISON: 'TOXIC_ARROW_POISON',
  TARANTULA_WEB: 'TARANTULA_WEB',
  TARANTULA_TALISMAN: 'TARANTULA_TALISMAN',
  FLY_SWATTER: 'FLY_SWATTER',
  OVERFLUX_CAPACITOR: 'OVERFLUX_CAPACITOR',
  GRIZZLY_BAIT: 'GRIZZLY_BAIT',
  WOLF_TOOTH: 'WOLF_TOOTH',
  HAMSTER_WHEEL: 'HAMSTER_WHEEL',
  SPIRIT_RUNE: 'SPIRIT_1_RUNE',
};

export const tiers = [
  {
    tier: 1,
    price: 100,
    xp: 5,
  },
  {
    tier: 2,
    price: 2000,
    xp: 25,
  },
  {
    tier: 3,
    price: 10000,
    xp: 100,
  },
  {
    tier: 4,
    price: 50000,
    xp: 500,
  },
];
